import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./pages/header/Header";
import Footer from "./pages/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-8 h-[100vh] flex flex-col `} >
        <div className=" bg-black  ">
          <Header></Header>
        </div>
        <div className="pt-10">
        {children}
        </div>  
        <div>
        </div>
      </body>
    </html>
  );
}
